[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  external_python_modules = [
    "boto3",
    "fpdf"
  ]

# Optional: Add specific configuration for your function
[functions."createCookbook.py"]
  memory = 128
  timeout = 10
